const fs = require("fs");

// Each locale is generated by an independent function whose require()/writeFileSync() paths are
// hard-coded string literals. No variable is ever interpolated into a path, so there is no path
// injection surface regardless of how these functions are called.

function writeLocale(zhCn, name) {
    const en = require('../out/i18n/en').default;
    const result = { ...en, ...zhCn };
    fs.writeFileSync('./i18n/' + name + '.ts',
        `import { __table } from './en';\r\n/*eslint sort-keys: "warn"*/\r\nconst table: Partial<typeof __table> = ` +
        JSON.stringify(result, Object.keys(result).sort(), 4) +
        `;\r\n\r\nexport default table;\r\n`
        );
}

function generateZhCn() {
    writeLocale(require('../out/i18n/zh-cn').default, 'zh-cn');
}

function generateKo() {
    writeLocale(require('../out/i18n/ko').default, 'ko');
}

function generateRu() {
    writeLocale(require('../out/i18n/ru').default, 'ru');
}

function generateTemplate() {
    writeLocale(require('../out/i18n/template').default, 'template');
}

generateZhCn();
generateKo();
generateRu();
generateTemplate();
